name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
